added autoshapes

diff --git a/.github/workflows/shacl.yaml b/.github/workflows/shacl.yaml
--- a/.github/workflows/shacl.yaml
+++ b/.github/workflows/shacl.yaml
@@ -33,6 +33,7 @@ jobs:
            for DIR in main/patterns/*/     
            do  
                if [[ "$DIR" != "main/patterns/unused/" ]]; then
+               if [[ "$DIR" != "main/patterns/autoshape/" ]]; then
                    echo "processing: $DIR"
 
                    SHAPEFILE="${DIR}shape.ttl"
@@ -40,5 +41,19 @@ jobs:
                    
                    java -jar robot.jar merge --collapse-import-closure false --input merged-pmdco.ttl --input "$DATAFILE" reason  --reasoner hermit --output shape-data-reasoned.ttl
                    python3 -m pyshacl  -s "$SHAPEFILE" shape-data-reasoned.ttl
+
+                   # test with autoshapes
+                   python3 -m pyshacl  -s ../autoshape/auto-shapes-open.ttl shape-data-reasoned.ttl
+
+                   # test that all classes in the a-box are present in PMDco ontology
+                   java -jar robot.jar robot export --input "$DATAFILE" --header "IRI" --include "classes properties" --export ids.txt
+                   tail -n +2 ids.txt > ids2.txt
+                   grep -Fof ids2.txt merged.ttl  | sort -u | grep  -Fvf - ids2.txt > missing.txt
+                   if [ -s missing.txt ]; then
+                      echo "Missing following IRIs in PMDco:"
+                      cat missing.txt
+                      exit 1
+                   fi
+               fi
                fi
            done
